language: java
cache:
  directories:
  - $HOME/.gradle

deploy:
  provider: script
  script: ./gradlew bintrayUpload
  skip_cleanup: true
  on:
    branch: master
    tags: true

after_success:
  - bash <(curl -s https://codecov.io/bash)
